apiVersion: apps/v1
kind: Deployment
metadata:
 name: vib-scheduler-consumer-vib-ms-7-days-deployment
 labels:
   app: vib-scheduler-consumer-vib-ms-7-days
spec:
 replicas: 1
 selector:
   matchLabels:
     app: vib-scheduler-consumer-vib-ms-7-days
 template:
   metadata:
     labels:
       app: vib-scheduler-consumer-vib-ms-7-days
   spec:
     containers:
       - name: vib-scheduler-consumer-vib-ms-7-days
         image: {image}
         command: ["/bin/sh", "-c"]
         args: ["cd $VIB_SCHEDULER_HOME; sh prepare_env.sh && python3.8 -u new_vib_consumer_services.py 'mobio-vib-most-spending-consumer' 'vib-ms-7days'"]
         resources:
           requests:
             memory: 30Mi
             cpu: 20m
           limits:
             memory: 1Gi
             cpu: 500m
         envFrom:
           - configMapRef:
               name: mobio-config
           - secretRef:
               name: mobio-secret
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc