apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-schedule-assign-send-mail-deployment
  labels:
    app: ticket-schedule-assign-send_mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-schedule-assign-send-mail
  template:
    metadata:
      labels:
        app: ticket-schedule-assign-send-mail
    spec:
      containers:
        - name: ticket
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $TICKET_HOME; sh prepare_env.sh && python3.8 -u start_schedulers.py ticket-scheduler-assignment-send-mail"]
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
            - name: mobio-public-shared-data
              mountPath: /media/data/public_resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
        - name: mobio-public-shared-data
          persistentVolumeClaim:
            claimName: mobio-public-resources-pvc