apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-consumer-listen-event-callcenter-relate-ticket-deployment
  labels:
    app: ticket-consumer-listen-event-callcenter-relate-ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-consumer-listen-event-callcenter-relate-ticket
  template:
    metadata:
      labels:
        app: ticket-consumer-listen-event-callcenter-relate-ticket
    spec:
      containers:
        - name: ticket
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $TICKET_HOME; sh prepare_env.sh && python3.8 -u start_consumers.py listen-event-callcenter-relate-ticket"]
          envFrom:
            - configMapRef:
                name: mobio-config
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
            - name: mobio-public-shared-data
              mountPath: /media/data/public_resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
        - name: mobio-public-shared-data
          persistentVolumeClaim:
            claimName: mobio-public-resources-pvc
