apiVersion: apps/v1
kind: Deployment
metadata:
  name: voucher-schedule-update-status-code-deployment
  labels:
    app: voucher-schedule-update-status-code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voucher-schedule-update-status-code
  template:
    metadata:
      labels:
        app: voucher-schedule-update-status-code
    spec:
      containers:
        - name: voucher
          image: {image}
          imagePullPolicy: Always
          command: [ "/bin/sh", "-c" ]
          args: [ "cd $VOUCHER_HOME; sh prepare_env.sh && python3.8 -u voucher_schedule_update_code_status.py" ]
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc