apiVersion: apps/v1
kind: Deployment
metadata:
  name: voucher-schedule-verify-code-file-deployment
  labels:
    app: voucher-schedule-verify-code-file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voucher-schedule-verify-code-file
  template:
    metadata:
      labels:
        app: voucher-schedule-verify-code-file
    spec:
      containers:
        - name: voucher
          image: {image}
          imagePullPolicy: Always
          command: [ "/bin/sh", "-c" ]
          args: [ "cd $VOUCHER_HOME; sh prepare_env.sh && python3.8 -u voucher_schedule_verify_code_file.py" ]
          envFrom:
            - configMapRef:
                name: mobio-config
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc