apiVersion: apps/v1
kind: Deployment
metadata:
 name: media-app-api-deployment
 labels:
   app: media-app-api
spec:
 replicas: 2
 selector:
   matchLabels:
     app: media-app-api
 template:
   metadata:
     labels:
       app: media-app-api
   spec:
     containers:
       - name: media
         image: {image}
         command: ["/bin/sh", "-c"]
         args: ["cd $MEDIA_HOME; sh prepare_env.sh && uwsgi --http :11220 --wsgi-file app_media.py --callable app --master --processes 4 -b 65536 --lazy --enable-threads"]
         envFrom:
           - configMapRef:
               name: mobio-config
         ports:
           - containerPort: 11220
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
           - name: mobio-public-shared-data
             mountPath: /media/data/public_resources/
         livenessProbe:
           httpGet:
             port: 11220
             path: /media/api/v1.0/ping
           initialDelaySeconds: 1
           periodSeconds: 5
           timeoutSeconds: 4
           failureThreshold: 3
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc
       - name: mobio-public-shared-data
         persistentVolumeClaim:
           claimName: mobio-public-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
 name: media-app-api-service
 labels:
   app: media-app-api
spec:
 ports:
  - name: old
    port: 11220
  - name: new
    port: 80
    protocol: TCP
    targetPort: 11220
 selector:
   app: media-app-api