apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiling-v4-schedule-re-register-audience-deployment
  labels:
    app: profiling-v4-schedule-re-register-audience
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profiling-v4-schedule-re-register-audience
  template:
    metadata:
      labels:
        app: profiling-v4-schedule-re-register-audience
    spec:
      containers:
        - name: profiling-v4
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $PROFILING_V4; sh prepare_env.sh && python3.8 -u start_profile_scheduler.py re-register-audience"]
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
               name: mobio-secret
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
          # livenessProbe:
          #   exec:
          #     command:
          #       - /bin/bash
          #       - -c
          #       - ps -ef | grep start_profile_scheduler.py | grep -v grep
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    