apiVersion: apps/v1
kind: Deployment
metadata:
  name: landingpage-schedule-retry-save-profile-deployment
  labels:
    app: landingpage-schedule-retry-save-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landingpage-schedule-retry-save-profile
  template:
    metadata:
      labels:
        app: landingpage-schedule-retry-save-profile
    spec:
      containers:
        - name: landingpage
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $LANDINGPAGE_HOME; sh prepare_env.sh && python3.8 -u k8s_start_scheduler.py"]
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    