apiVersion: apps/v1
kind: Deployment
metadata:
 name: landingpage-consumer-ladipage-fillform-deployment
 labels:
   app: landingpage-consumer-ladipage-fillform
spec:
 replicas: 2
 selector:
   matchLabels:
     app: landingpage-consumer-ladipage-fillform
 template:
   metadata:
     labels:
       app: landingpage-consumer-ladipage-fillform
   spec:
     containers:
       - name: landingpage
         image: {image}
         imagePullPolicy: Always
         command: ["/bin/sh", "-c"]
         args: ["cd $LANDINGPAGE_HOME; sh prepare_env.sh && python3.8 -u app_consumer_ladipage_fillform.py"]
         resources:
           requests:
             memory: 70Mi
             cpu: 80m
           limits:
             memory: 1Gi
             cpu: 500m
         envFrom:
           - configMapRef:
               name: mobio-config
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc