apiVersion: apps/v1
kind: Deployment
metadata:
 name: social-app-webhook-deploy
 labels:
   app: social-app-webhook
spec:
 replicas: 2
 selector:
   matchLabels:
     app: social-app-webhook
 template:
   metadata:
     labels:
       app: social-app-webhook
   spec:
     containers:
       - name: social
         image: {image}
         imagePullPolicy: Always
         command: ["/bin/sh", "-c"]
         args: ["cd $SOCIAL_HOME; sh prepare_env.sh && uwsgi --http :11111 --wsgi-file app_webhook_social.py --callable app --master --processes 4 -b 65536 --lazy --enable-threads"]
         resources:
           requests:
             memory: 30Mi
             cpu: 20m
           limits:
             memory: 1Gi
             cpu: 500m
         envFrom:
           - configMapRef:
               name: mobio-config
           - secretRef:
               name: mobio-secret
         ports:
           - containerPort: 11111
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
         livenessProbe:
           httpGet:
             port: 11111
             path: /api/v1.0/ping
           initialDelaySeconds: 5
           periodSeconds: 5
           timeoutSeconds: 4
           successThreshold: 1
           failureThreshold: 3
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
 name: social-webhook-app-service
 labels:
   app: social-app-webhook
spec:
 ports:
   - port: 11111
     name: old
   - port: 80
     name: new
     protocol: TCP
     targetPort: 11111
 selector:
   app: social-app-webhook