apiVersion: apps/v1
kind: Deployment
metadata:
 name: social-consumer-line-message-deploy
 labels:
   app: social-consumer-line-message
spec:
 replicas: 1
 selector:
   matchLabels:
     app: social-consumer-line-message
 template:
   metadata:
     labels:
       app: social-consumer-line-message
   spec:
     containers:
       - name: social
         image: {image}
         imagePullPolicy: Always
         command: ["/bin/sh", "-c"]
         args: ["cd $SOCIAL_HOME; sh prepare_env.sh && python3.5 -u social_line_message_v2_consumer.py"]
         resources:
           requests:
             memory: 70Mi
             cpu: 80m
           limits:
             memory: 1Gi
             cpu: 500m
         resources:
           requests:
             memory: 70Mi
             cpu: 80m
           limits:
             memory: 1Gi
             cpu: 500m
         envFrom:
           - configMapRef:
               name: mobio-config
           - secretRef:
               name: mobio-secret
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc