apiVersion: apps/v1
kind: Deployment
metadata:
  name: emk-app-api-deployment
  labels:
    app: emk-app-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emk-app-api
  template:
    metadata:
      labels:
        app: emk-app-api
    spec:
      containers:
        - name: emk
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $EMK_HOME; sh prepare_env.sh && uwsgi --http :11040 --wsgi-file app_emk.py --master --processes 4 -b 65536 --lazy --enable-threads"]
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          ports:
            - containerPort: 11040
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
            - name: mobio-public-shared-data
              mountPath: /media/data/public_resources/
          readinessProbe:
            httpGet:
              port: 11040
              path: /api/v1.0/ping
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 3
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
        - name: mobio-public-shared-data
          persistentVolumeClaim:
            claimName: mobio-public-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: emk-app-api-service
  labels:
    app: emk-app-api
spec:
  ports:
    - name: old
      port: 11040
    - name: new
      port: 80
      targetPort: 11040
  selector:
    app: emk-app-api