pool:
  name	: $(selfAgentPool)

variables:
- group: prod-var-connections

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - scripting/*

stages:
- stage: Init
  jobs:
  - job: Init
    steps:
    - bash: |
        cd scripting
        chmod +x script-download-images.sh
        ./script-download-images.sh	
      displayName: 'Run pull images script'
    
    - task: Docker@2
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        command: 'login'
      displayName: 'Login ACR'
    
    - bash: |
        cd scripting
        chmod +x script-push-images.sh
        ./script-push-images.sh
      displayName: 'Run push images script'