pool:
  name	: azure-hk-agentpool-prod-prv-001

stages:
- stage: Init
  jobs:
  - job: Init
    steps:
    - bash: | 
        ./script-download-images.sh	
      displayName: 'Run pull images script'
    
    - task: Docker@2
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        command: 'login'
      displayName: 'Login ACR'
    
    - bash: |
        ./script-push-images.sh
      displayName: 'Run push images script'