pool:
  name	: $(selfAgentPool)

variables:
- group: prod-var-connections

trigger: none

stages:
- stage: Init
  jobs:
  - job: Init
    steps:
    - task: Kubernetes@1
      displayName: kubectl apply
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: $(kubernetesServiceConnection)
        namespace: $(nameSpace)
        command: apply
        arguments: -f base/pv.yaml

    - task: Kubernetes@1
      displayName: kubectl apply
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: $(kubernetesServiceConnection)
        namespace: $(nameSpace)
        command: apply
        arguments: -f base/pvc.yaml