apiVersion: apps/v1
kind: Deployment
metadata:
  name: journey-builder-app-tracking-url-deployment
  labels:
    app: journey-builder-app-tracking-url
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journey-builder-app-tracking-url
  template:
    metadata:
      labels:
        app: journey-builder-app-tracking-url
    spec:
      containers:
        - name: journey
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $JOURNEY_HOME; sh prepare_env.sh; uwsgi --http :11193 --wsgi-file app_tracking_url.py --callable app --master --processes 4 -b 65536 --lazy --enable-threads"]
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          ports:
            - containerPort: 11193
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
          readinessProbe:
            httpGet:
              port: 11193
              path: /api/v1.0/ping
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 4
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: journey-builder-app-tracking-url-service
  labels:
    app: journey-builder-app-tracking-url
spec:
  ports:
    - name: old
      port: 11193
    - name: new
      port: 80
  selector:
    app: journey-builder-app-tracking-url