apiVersion: apps/v1
kind: Deployment
metadata:
  name: journey-builder-app-internal-deployment
  labels:
    app: journey-builder-app-internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journey-builder-app-internal
  template:
    metadata:
      labels:
        app: journey-builder-app-internal
    spec:
      containers:
        - name: journey
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $JOURNEY_HOME; sh prepare_env.sh && uwsgi --http :11192 --wsgi-file app_internal.py --callable app --master --processes 4 -b 65536 --lazy --enable-threads"]
          envFrom:
            - configMapRef:
                name: mobio-config
          ports:
            - containerPort: 11192
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
          readinessProbe:
            httpGet:
              port: 11192
              path: /api/v1.0/ping
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 4
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: journey-builder-app-internal-service
  labels:
    app: journey-builder-app-internal
spec:
  ports:
    - name: old
      port: 11192
    - name: new
      port: 80
  selector:
    app: journey-builder-app-internal