
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  namespace: mobio
  name: prof-fac-consumer-jb-dist-vib-tot-spen-scaledobject
spec:
  scaleTargetRef:
    kind: Deployment
    name: prof-fac-consumer-jb-dist-vib-tot-spen-deployment
  pollingInterval: 30
  cooldownPeriod: 300
  maxReplicaCount: 4
  minReplicaCount: 1
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka1:9092,kafka2:9092,kafka3:9092
        consumerGroup: factory-jb-vib-total-spending-pre-process
        topic: factory-jb-dist-vib-tot-spen
        lagThreshold: '1000'
        offsetResetPolicy: latest
        allowIdleConsumers: 'true'
        version: 2.1.1
    