apiVersion: v1
kind: ConfigMap
metadata:
  name: monstache-ticket-v1-1-config
data:
  ticket.conf: |
     gzip = true
     mongo-url = "mongodb://_MONGO_USER_:_MONGO_PASSWORD_@mongo1:27017,mongo2:27017,mongo3:27017/?readPreference=secondaryPreferred"
     elasticsearch-urls = ["http://_ELASTIC_SEARCH_HOST_:_ELASTIC_SEARCH_PORT_"]
     elasticsearch-max-conns = 4
     change-stream-namespaces = ["Ticket.ticket"]
     direct-read-namespaces = ["Ticket.ticket"]
     direct-read-stateful = true
     verbose = true
     resume = true
     resume-strategy = 1
     resume-name="monstache-ticket-v1-1-pod"
     [logs]
     error = "/dev/stderr"
     [[mapping]]
     namespace="Ticket.ticket"
     index="mobio-ticket-v1_1"
     type="p_raw"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monstache-ticket-v1-1-deploy
  labels:
    app: monstache-ticket-v1-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monstache-ticket-v1-1
  template:
    metadata:
      labels:
        app: monstache-ticket-v1-1
    spec:
      containers:
        - image: {image}
          name: monstache-ticket-v1-1
          args: ["/home/mobio/ticket.conf"]
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 2Gi
              cpu: 500m
          envFrom:
           - configMapRef:
              name: mobio-config

          volumeMounts:
            - name: config
              mountPath: /home/mobio/ticket.conf
              subPath: ticket.conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: monstache-ticket-v1-1-config
      imagePullSecrets:
        - name: registrypullsecret