apiVersion: v1
kind: ConfigMap
metadata:
  name: monstache-vib-schedule-v2-config
data:
  vib_schedule.conf: |
    gzip = true

    mongo-url = "mongodb://_MONGO_USER_:_MONGO_PASSWORD_@mongo1:27017,mongo2:27017,mongo3:27017/?readPreference=secondaryPreferred"

    elasticsearch-urls = ["http://_ELASTIC_SEARCH_HOST_:_ELASTIC_SEARCH_PORT_"]

    elasticsearch-max-conns = 4

    change-stream-namespaces = ["vib_schedule.vib_spend_group"]
    direct-read-namespaces = ["vib_schedule.vib_spend_group"]
    direct-read-stateful = true

    resume = true
    resume-strategy = 1
    resume-name="monstache-vib-schedule-v2-pod"

    [logs]
    error = "/dev/stderr"

    [[mapping]]
    namespace="vib_schedule.vib_spend_group"
    index="vib_schedule_v2"
    type="vib_spend_group"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monstache-vib-schedule-v2-deploy
    labels:
      app: monstache-vib-schedule-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monstache-vib-schedule-v2
  template:
    metadata:
      labels:
        app: monstache-vib-schedule-v2
    spec:
      containers:
        - image: registry.mobio.vn/mobio_monstache:5
          name: monstache-vib-schedule-v2
          args: ["/home/mobio/vib_schedule.conf"]
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 2Gi
              cpu: 500m
          envFrom:
           - configMapRef:
              name: mobio-config

          volumeMounts:
            - name: config
              mountPath: /home/mobio/vib_schedule.conf
              subPath: vib_schedule.conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: monstache-vib-schedule-v2-config
      imagePullSecrets:
        - name: registrypullsecret
