apiVersion: v1
kind: ConfigMap
metadata:
  name: monstache-profiling-report-v1-1-config
data:
  profiling_report.conf: |
    gzip = true

    mongo-url = "mongodb://_MONGO_USER_:_MONGO_PASSWORD_@mongo1:27017,mongo2:27017,mongo3:27017/?readPreference=secondaryPreferred"

    elasticsearch-urls = ["http://_ELASTIC_SEARCH_HOST_:_ELASTIC_SEARCH_PORT_"]

    elasticsearch-max-conns = 4

    change-stream-namespaces = ["profiling.profiling_report"]
    direct-read-namespaces = ["profiling.profiling_report"]
    direct-read-stateful = true

    resume = true
    resume-strategy = 1
    resume-name="monstache-profiling-report-v1-1-pod"

    [logs]
    error = "/dev/stderr"

    [[mapping]]
    namespace="profiling.profiling_report"
    index="profiling-report-v1_1"
    type="p_raw"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monstache-profiling-report-v1-1-deploy
  labels:
    app: monstache-profiling-report-v1-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monstache-profiling-report-v1-1
  template:
    metadata:
      labels:
        app: monstache-profiling-report-v1-1
    spec:
      containers:
        - image: registry.mobio.vn/mobio_monstache:5
          name: monstache-profiling-report-v1-1
          args: ["/home/mobio/profiling_report.conf"]
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 2Gi
              cpu: 500m
          envFrom:
           - configMapRef:
              name: mobio-config

          volumeMounts:
            - name: config
              mountPath: /home/mobio/profiling_report.conf
              subPath: profiling_report.conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: monstache-profiling-report-v1-1-config
      imagePullSecrets:
        - name: registrypullsecret
