apiVersion: v1
kind: ConfigMap
metadata:
  name: monstache-journey-report-link-v1-0-config
data:
  journey_report_link.conf: |
    gzip = true
    mongo-url = "mongodb://_MONGO_USER_:_MONGO_PASSWORD_@mongo1:27017,mongo2:27017,mongo3:27017/?readPreference=secondaryPreferred"
    elasticsearch-urls = ["http://_ELASTIC_SEARCH_HOST_:_ELASTIC_SEARCH_PORT_"]
    elasticsearch-max-conns = 4
    change-stream-namespaces = ["journey_builder.report_link"]
    direct-read-namespaces = ["journey_builder.report_link"]
    direct-read-stateful = true
    verbose = true
    resume = true
    resume-strategy = 1
    resume-name="monstache-journey-report-link-v1-0-pod"
    [logs]
    error = "/dev/stderr"
    [[mapping]]
    namespace="journey_builder.report_link"
    index="journey-report-link"
    type="link"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monstache-journey-report-link-v1-0-deploy
  labels:
    app: monstache-journey-report-link-v1-0-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monstache-journey-report-link-v1-0-pod
  template:
    metadata:
      labels:
        app: monstache-journey-report-link-v1-0-pod
    spec:
      containers:
        - image: {image}
          name: monstache-journey-report-link-v1-0-pod
          args: ["/home/mobio/journey_report_link.conf"]
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 2Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
          volumeMounts:
            - name: monstache-journey-report-link-v1-0-config
              mountPath: /home/mobio/journey_report_link.conf
              subPath: journey_report_link.conf
              readOnly: true

      volumes:
        - name: monstache-journey-report-link-v1-0-config
          configMap:
            name: monstache-journey-report-link-v1-0-config
      imagePullSecrets:
        - name: registrypullsecret