apiVersion: v1
kind: ConfigMap
metadata:
  name: monstache-profiling-v16-3-config
data:
  profiling.conf: |
    gzip = true

    mongo-url = "mongodb://_MONGO_USER_:_MONGO_PASSWORD_@mongo1:27017,mongo2:27017,mongo3:27017/?readPreference=secondaryPreferred"

    elasticsearch-urls = ["http://_ELASTIC_SEARCH_HOST_:_ELASTIC_SEARCH_PORT_"]

    elasticsearch-max-conns = 4

    change-stream-namespaces = ["profiling.profile_raw_data"]
    direct-read-namespaces = ["profiling.profile_raw_data"]
    direct-read-stateful = true

    resume = true
    resume-strategy = 1
    resume-name="monstache-profiling-v16-3-pod"

    [logs]
    error = "/dev/stderr"

    [[mapping]]
    namespace="profiling.profile_raw_data"
    index="mobio-profiling-v16_3"
    type="p_raw"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monstache-profiling-v16-3-deploy
  labels:
    app: monstache-profiling-v16-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monstache-profiling-v16-3
  template:
    metadata:
      labels:
        app: monstache-profiling-v16-3
    spec:
      containers:
        - image: {image}
          name: monstache-profiling-v16-3
          args: ["/home/mobio/profiling.conf"]
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 2Gi
              cpu: 500m
          envFrom:
           - configMapRef:
              name: mobio-config

          volumeMounts:
            - name: config
              mountPath: /home/mobio/profiling.conf
              subPath: profiling.conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: monstache-profiling-v16-3-config
      imagePullSecrets:
        - name: registrypullsecret
