apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-onpremise-api
  namespace: mobio
spec:
  selector:
    matchLabels:
      app: nginx-onpremise-api
  template:
    metadata:
      labels:
        app: nginx-onpremise-api
    spec:
      containers:
        - name: nginx-onpremise-api
          image: {image}
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          envFrom:
            - configMapRef:
                name: mobio-config              
#      volumes:
#      imagesPullSecrets:
#        - name: registrypullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-onpremise-service
  namespace: mobio
  labels:
    app: nginx-onpremise-api
spec:
  type: NodePort
  selector:
    app: nginx-onpremise-api
  ports:
    - name: http
      port: 80
      nodePort: 30080
    - name: https
      port: 443
      nodePort: 30443

