apiVersion: apps/v1
kind: Deployment
metadata:
  name: callcenter-app-api-deployment
  labels:
    app: callcenter-app-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: callcenter-app-api
  template:
    metadata:
      labels:
        app: callcenter-app-api
    spec:
      containers:
        - name: callcenter
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $CALLCENTER_HOME; sh prepare_env.sh && uwsgi --http :11160 --wsgi-file app_callcenter.py --callable app --master --processes 4 -b 65536 --lazy --enable-threads"]
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          ports:
            - containerPort: 11160
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 1Gi
              cpu: 500m
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
            - name: mobio-public-shared-data
              mountPath: /media/data/public_resources/
          livenessProbe:
            httpGet:
              port: 11160
              path: /callcenter/api/v2.0/ping
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 3
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
        - name: mobio-public-shared-data
          persistentVolumeClaim:
            claimName: mobio-public-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: callcenter-app-api-service
  labels:
    app: callcenter-app-api
spec:
  ports:
    - name: old
      port: 11160
    - name: new
      port: 80
      protocol: TCP
      targetPort: 11160
  selector:
    app: callcenter-app-api