apiVersion: apps/v1
kind: Deployment
metadata:
  name: callcenter-schedule-cc-e45-aggregate-report-deployment
  labels:
    app: callcenter-schedule-cc-e45-aggregate-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: callcenter-schedule-cc-e45-aggregate-report
  template:
    metadata:
      labels:
        app: callcenter-schedule-cc-e45-aggregate-report
    spec:
      containers:
        - name: callcenter
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $CALLCENTER_HOME; sh prepare_env.sh && python3.8 -u k8s_start_scheduler.py cc-e45-aggregate-report"]
          resources:
            requests:
                memory: 30Mi
                cpu: 20m
            limits:
                memory: 1Gi
                cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
               name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
            - name: mobio-public-shared-data
              mountPath: /media/data/public_resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
        - name: mobio-public-shared-data
          persistentVolumeClaim:
            claimName: mobio-public-resources-pvc
    