apiVersion: apps/v1
kind: Deployment
metadata:
  name: callcenter-schedule-download-audio-call-deployment
  labels:
    app: callcenter-schedule-download-audio-call
spec:
  replicas: 1
  selector:
    matchLabels:
      app: callcenter-schedule-download-audio-call
  template:
    metadata:
      labels:
        app: callcenter-schedule-download-audio-call
    spec:
      containers:
        - name: callcenter
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $CALLCENTER_HOME; sh prepare_env.sh && python3.8 -u k8s_start_scheduler.py download-audio-call"]
          resources:
            requests:
                memory: 70Mi
                cpu: 80m
            limits:
                memory: 1Gi
                cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
            - name: mobio-public-shared-data
              mountPath: /media/data/public_resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
        - name: mobio-public-shared-data
          persistentVolumeClaim:
            claimName: mobio-public-resources-pvc
    