apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnc-consumer-dnc-e1-event-deployment
  labels:
    app: dnc-consumer-dnc-e1-event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnc-consumer-dnc-e1-event
  template:
    metadata:
      labels:
        app: dnc-consumer-dnc-e1-event
    spec:
      containers:
        - name: dnc
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $DONOTCALL_HOME; sh prepare_env.sh && python3.8 -u k8s_consumer_start.py dnc-e1-event"]
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    