apiVersion: v1
kind: PersistentVolume
metadata:
  name: mobio-public-resources-pv
  labels:
    pv: mobio-public-resources-shared-deployment
spec:
  capacity:
    storage: 50G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain    
  azureFile:
    # Replace with your secret name
    secretName: azurefilemktgsecret
    # Replace with correct storage share name
    shareName: mktg-data01
    # In case the secret is stored in a different namespace
    secretNamespace: mobio
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mobio-resoures-pv
  labels:
    pv: mobio-resources-shared-deployment
spec:
  capacity:
    storage: 50G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain    
  azureFile:
    # Replace with your secret name
    secretName: azurefilemktgsecret
    # Replace with correct storage share name
    shareName: mktg-data02
    # In case the secret is stored in a different namespace
    secretNamespace: mobio
    readOnly: false
