apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobio-resources-pvc
  namespace: mobio
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  resources:
    requests:
      storage: 50G
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      pv: mobio-resources-shared-deployment

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobio-public-resources-pvc
  namespace: mobio
  annotations:
    volume.beta.kubernetes.io/storage-class: ""  
spec:
  resources:
    requests:
      storage: 50G
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      pv: mobio-public-resources-shared-deployment