apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-factory-consumer-jb-popup-submit-form-proc-brcast-deployment
  labels:
    app: profile-factory-consumer-jb-popup-submit-form-proc-brcast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-factory-consumer-jb-popup-submit-form-proc-brcast
  template:
    metadata:
      labels:
        app: profile-factory-consumer-jb-popup-submit-form-proc-brcast
    spec:
      containers:
        - name: profile-factory
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $FACTORY_HOME; sh prepare_env.sh && PYTHONPATH=./ python3.5 -u run_consumer/factory_consumer_jb_popup_submit_form_proc_brcast.py -r 1"]
          envFrom:
            - configMapRef:
                name: mobio-config
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
          # livenessProbe:
          #   exec:
          #     command:
          #       - /bin/bash
          #       - -c
          #       - ps -ef | grep run_consumer/factory_consumer_jb_popup_submit_form_proc_brcast.py | grep -v grep
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    