apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-factory-consumer-jb-tran-ewal-quantity-result-deployment
  labels:
    app: profile-factory-consumer-jb-tran-ewal-quantity-result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-factory-consumer-jb-tran-ewal-quantity-result
  template:
    metadata:
      labels:
        app: profile-factory-consumer-jb-tran-ewal-quantity-result
    spec:
      containers:
        - name: profile-factory
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $FACTORY_HOME; sh prepare_env.sh && PYTHONPATH=./ python3.5 -u run_consumer/factory_consumer_jb_tran_ewal_quantity_result.py -r 1"]
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
               name: mobio-secret
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 1Gi
              cpu: 500m
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
          # livenessProbe:
          #   exec:
          #     command:
          #       - /bin/bash
          #       - -c
          #       - ps -ef | grep run_consumer/factory_consumer_jb_tran_ewal_quantity_result.py | grep -v grep
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    