apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-factory-schedule-f1-scheduler-new-special-day-scan-deployment
  labels:
    app: profile-factory-schedule-f1-scheduler-new-special-day-scan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-factory-schedule-f1-scheduler-new-special-day-scan
  template:
    metadata:
      labels:
        app: profile-factory-schedule-f1-scheduler-new-special-day-scan
    spec:
      containers:
        - name: profile-factory
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $FACTORY_HOME; sh prepare_env.sh && PYTHONPATH=./ python3.5 -u run_scheduler/factory_scheduler_f1_scheduler_new_special_day_scan.py"]
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
               name: mobio-secret
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 1Gi
              cpu: 500m
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    