apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobio-report-app-api-deployment
  labels:
    app: mobio-report-app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobio-report-app-api
  template:
    metadata:
      labels:
        app: mobio-report-app-api
    spec:
      containers:
        - name: mobio-report
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $MOBIO_REPORT_HOME; sh prepare_env.sh && uwsgi --http :11250 --wsgi-file api_services.py --callable app --master --processes 4 -b 65536 --lazy --enable-threads"]
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          ports:
            - containerPort: 11250
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
          livenessProbe:
            httpGet:
              port: 11250
              path: /rapporteur/api/v1.0/ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 4
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mobio-report-app-api-service
  labels:
    app: mobio-report-app-api
spec:
  clusterIP: None
  ports:
    - name: old
      port: 11250
    - name: new
      port: 80
      protocol: TCP
      targetPort: 11250
  selector:
    app: mobio-report-app-api