apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-publicgateway-api
spec:
  selector:
    matchLabels:
      app: nginx-publicgateway-api
  template:
    metadata:
      labels:
        app: nginx-publicgateway-api
    spec:
      containers:
        - name: nginx-publicgateway-api
          image: {image}
          ports:
            - name: https
              containerPort: 443
          envFrom:
            - configMapRef:
                name: mobio-config              
          volumeMounts:
            - name: mobio-public-shared-data
              mountPath: /media/data/public_resources/
      volumes:
        - name: mobio-public-shared-data
          persistentVolumeClaim:
            claimName: mobio-public-resources-pvc
      imagePullSecrets:
        - name: registrypullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-publicgateway-service
  labels:
    app: nginx-publicgateway-api
spec:
  type: NodePort
  selector:
    app: nginx-publicgateway-api
  ports:
    - name: https
      port: 443
      nodePort: 30441
