apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketing-app-experiment-url-deployment
  labels:
    app: marketing-app-experiment-url
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marketing-app-experiment-url
  template:
    metadata:
      labels:
        app: marketing-app-experiment-url
    spec:
      containers:
        - name: marketingv3
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $MARKETING_HOME; sh prepare_env.sh && uwsgi --http :11063 --wsgi-file app_experiment_url.py --callable app_experiment_url --master --processes 4 -b 65536 --lazy --enable-threads"]
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          ports:
            - containerPort: 11063
          imagePullPolicy: Always
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
          livenessProbe:
            httpGet:
              port: 11063
              path: /api/v1.0/ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 4
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: marketing-app-experiment-url-service
  labels:
    app: marketing-app-experiment-url
spec:
  clusterIP: None
  ports:
    - port: 11063
  selector:
    app: marketing-app-experiment-url