apiVersion: apps/v1
kind: Deployment
metadata:
 name: marketing-consumer-socket-report-deployment
 labels:
   app: marketing-consumer-socket-report
spec:
 replicas: 1
 selector:
   matchLabels:
     app: marketing-consumer-socket-report
 template:
   metadata:
     labels:
       app: marketing-consumer-socket-report
   spec:
     containers:
       - name: marketingv3
         image: {image}
         command: ["/bin/sh", "-c"]
         args: ["cd $MARKETING_HOME; sh prepare_env.sh && python3.5 -u mkt_consumer_socket_report.py"]
         envFrom:
           - configMapRef:
               name: mobio-config
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc