apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-consumer-ticket-assignment-internal-team-deployment
  labels:
    app: ticket-consumer-ticket-assignment-internal-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-consumer-ticket-assignment-internal-team
  template:
    metadata:
      labels:
        app: ticket-consumer-ticket-assignment-internal-team
    spec:
      containers:
        - name: ticket
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $TICKET_HOME; sh prepare_env.sh && python3.8 -u start_consumers.py ticket_assignment_internal_team"]
          envFrom:
            - configMapRef:
                name: mobio-config
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
            - name: mobio-public-shared-data
              mountPath: /media/data/public_resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
        - name: mobio-public-shared-data
          persistentVolumeClaim:
            claimName: mobio-public-resources-pvc
