apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-consumer-assign-rule-default-deployment
  labels:
    app: ticket-consumer-assign-rule-default-assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-consumer-assign-rule-default-assignment
  template:
    metadata:
      labels:
        app: ticket-consumer-assign-rule-default-assignment
    spec:
      containers:
        - name: ticket
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $TICKET_HOME; sh prepare_env.sh && python3.8 -u start_consumers.py ticket_assign_rule_default"]
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
            - name: mobio-public-shared-data
              mountPath: /media/data/public_resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
        - name: mobio-public-shared-data
          persistentVolumeClaim:
            claimName: mobio-public-resources-pvc
