apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-consumer-automation-action-send-notify-internal-deployment
  labels:
    app: ticket-consumer-automation-action-send-notify-internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-consumer-automation-action-send-notify-internal
  template:
    metadata:
      labels:
        app: ticket-consumer-automation-action-send-notify-internal
    spec:
      containers:
        - name: ticket
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $TICKET_HOME; sh prepare_env.sh && python3.8 -u start_consumers.py ticket_handle_action_send_notify_internal"]
          envFrom:
            - configMapRef:
                name: mobio-config
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
            - name: mobio-public-shared-data
              mountPath: /media/data/public_resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
        - name: mobio-public-shared-data
          persistentVolumeClaim:
            claimName: mobio-public-resources-pvc
