apiVersion: apps/v1
kind: Deployment
metadata:
  name: journey-scheduler-wait-processing-journey-deployment
  labels:
    app: journey-scheduler-wait-processing-journey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journey-scheduler-wait-processing-journey
  template:
    metadata:
      labels:
        app: journey-scheduler-wait-processing-journey
    spec:
      containers:
        - name: journey
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $JOURNEY_HOME; sh prepare_env.sh && python3.8 -u jb_job_services.py jb-wait-process-scheduler"]
          envFrom:
            - configMapRef:
                name: mobio-config
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    