apiVersion: apps/v1
kind: Deployment
metadata:
  name: journey-scheduler-send-notify-journey-deployment
  labels:
    app: journey-scheduler-send-notify-journey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journey-scheduler-send-notify-journey
  template:
    metadata:
      labels:
        app: journey-scheduler-send-notify-journey
    spec:
      containers:
        - name: journey
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $JOURNEY_HOME; sh prepare_env.sh && python3.8 -u jb_job_services.py jb-send-notify-scheduler"]
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    