apiVersion: apps/v1
kind: Deployment
metadata:
  name: tag-consumer-tag-e9-msg-bus-aggregate-tag-used-deployment
  labels:
    app: tag-consumer-tag-e9-msg-bus-aggregate-tag-used
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tag-consumer-tag-e9-msg-bus-aggregate-tag-used
  template:
    metadata:
      labels:
        app: tag-consumer-tag-e9-msg-bus-aggregate-tag-used
    spec:
      containers:
        - name: tag
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $TAG_HOME; sh prepare_env.sh && python3.8 -u k8s_consumer_start.py tag-e9-msg-bus-aggregate-tag-used"]
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
               name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    