apiVersion: apps/v1
kind: Deployment
metadata:
  name: tag-schedule-tag-e9-get-merchant-aggregate-deployment
  labels:
    app: tag-schedule-tag-e9-get-merchant-aggregate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tag-schedule-tag-e9-get-merchant-aggregate
  template:
    metadata:
      labels:
        app: tag-schedule-tag-e9-get-merchant-aggregate
    spec:
      containers:
        - name: tag
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $TAG_HOME; sh prepare_env.sh && python3.8 -u k8s_start_scheduler.py tag-e9-get-merchant-aggregate"]
          envFrom:
            - configMapRef:
                name: mobio-config
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    