apiVersion: apps/v1
kind: Deployment
metadata:
  name: nm-app-api-deployment
  labels:
    app: nm-app-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nm-app-api
  template:
    metadata:
      labels:
        app: nm-app-api
    spec:
      containers:
        - name: nm
          image: {image}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["cd $NOTIFY_MANAGER_V2; sh prepare_env.sh && uwsgi --http :11071 --wsgi-file nm_api_app.py --callable app --master --processes 4 -b 65536 --lazy --enable-threads"]
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          ports:
            - containerPort: 11071
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
          livenessProbe:
            httpGet:
              port: 11071
              path: /api/v1.0/ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 4
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nm-app-api-service
  labels:
    app: nm-app-api
spec:
  ports:
    - name: old
      port: 11071
    - name: new
      port: 80
      protocol: TCP
      targetPort: 11071
  selector:
    app: nm-app-api