apiVersion: apps/v1
kind: Deployment
metadata:
  name: nm-scheduler-underground-runtime-deployment
  labels:
    app: nm-scheduler-underground-runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nm-scheduler-underground-runtime
  template:
    metadata:
      labels:
        app: nm-scheduler-underground-runtime
    spec:
      containers:
        - name: nm
          image: {image}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["cd $NOTIFY_MANAGER_V2; sh prepare_env.sh && python3.8 -u nm_underground_runtime.py notify fb_message log_cleaner socket_health_check import_file"]
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc