apiVersion: apps/v1
kind: Deployment
metadata:
  name: nm-consumers-start-check-valid-deployment
  labels:
    app: nm-consumers-start-check-valid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nm-consumers-start-check-valid
  template:
    metadata:
      labels:
        app: nm-consumers-start-check-valid
    spec:
      containers:
        - name: nm
          image: {image}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["cd $NOTIFY_MANAGER_V2; sh prepare_env.sh && python3.8 -u nm_consumer_services.py nm_check_email_valid 1"]
          envFrom:
            - configMapRef:
                name: mobio-config
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc