apiVersion: apps/v1
kind: Deployment
metadata:
  name: nm-consumer-sent-notify-deployment
  labels:
    app: nm-consumer-sent-notify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nm-consumer-sent-notify
  template:
    metadata:
      labels:
        app: nm-consumer-sent-notify
    spec:
      containers:
        - name: nm
          image: {image}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["cd $NOTIFY_MANAGER_V2; sh prepare_env.sh && python3.8 -u nm_consumer_services.py nm_v2_sent_notify 1"]
          envFrom:
            - configMapRef:
                name: mobio-config
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
            - name: mobio-public-shared-data
              mountPath: /media/data/public_resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
        - name: mobio-public-shared-data
          persistentVolumeClaim:
            claimName: mobio-public-resources-pvc