apiVersion: apps/v1
kind: Deployment
metadata:
  name: nm-consumer-nm-callback-msb-event-deployment
  labels:
    app: nm-consumer-nm-callback-msb-event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nm-consumer-nm-callback-msb-event
  template:
    metadata:
      labels:
        app: nm-consumer-nm-callback-msb-event
    spec:
      containers:
        - name: nm
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $NOTIFY_MANAGER_V2; sh prepare_env.sh && python3.8 -u nm_consumer_services.py notification-status-sync 1"]
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    