apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-schedule-sync-google-calendar-event-deployment
  labels:
    app: admin-schedule-sync-google-calendar-event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-schedule-sync-google-calendar-event
  template:
    metadata:
      labels:
        app: admin-schedule-sync-google-calendar-event
    spec:
      containers:
        - name: admin
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $ADMIN_HOME; sh prepare_env.sh && python3.8 -u k8s_start_scheduler.py sync-google-calendar-event"]
          resources:
            requests:
                memory: 70Mi
                cpu: 80m
            limits:
                memory: 1Gi
                cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    