apiVersion: apps/v1
kind: Deployment
metadata:
 name: admin-app-webhook-deployment
 labels:
   app: admin-app-webhook
spec:
 replicas: 2
 selector:
   matchLabels:
     app: admin-app-webhook
 template:
   metadata:
     labels:
       app: admin-app-webhook
   spec:
     containers:
       - name: admin
         image: {image}
         imagePullPolicy: Always
         command: ["/bin/sh", "-c"]
         args: ["cd $ADMIN_HOME; sh prepare_env.sh && uwsgi --http :11001 --wsgi-file app_webhook_administration.py --callable app_administration --master --processes 4 -b 65536 --lazy --enable-threads"]
         envFrom:
           - configMapRef:
               name: mobio-config
           - secretRef:
               name: mobio-secret
         ports:
           - containerPort: 11001
         resources:
           requests:
             memory: 30Mi
             cpu: 20m
           limits:
             memory: 1Gi
             cpu: 500m
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
         livenessProbe:
           httpGet:
             port: 11001
             path: /api/v2.1/ping
           initialDelaySeconds: 120
           periodSeconds: 5
           timeoutSeconds: 4
           failureThreshold: 3
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
 name: admin-app-webhook-service
 labels:
   app: admin-app-webhook
spec:
 ports:
   - name: old
     port: 11001
   - name: new
     port: 80
     protocol: TCP
     targetPort: 11001
 selector:
   app: admin-app-webhook