apiVersion: apps/v1
kind: Deployment
metadata:
 name: admin-alert-merchant-scheduler-deployment
 labels:
   app: admin-alert-merchant-scheduler
spec:
 replicas: 1
 selector:
   matchLabels:
     app: admin-alert-merchant-scheduler
 template:
   metadata:
     labels:
       app: admin-alert-merchant-scheduler
   spec:
     containers:
       - name: admin
         image: {image}
         imagePullPolicy: Always
         command: ["/bin/sh", "-c"]
         args: ["cd $ADMIN_HOME; sh prepare_env.sh && python3.8 -u admin_alert_merchant.py"]
         resources:
           requests:
             memory: 70Mi
             cpu: 80m
           limits:
             memory: 1Gi
             cpu: 500m
         envFrom:
           - configMapRef:
               name: mobio-config
           - secretRef:
               name: mobio-secret
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc
