apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiling-v4-consumer-vib-add-campaign-profile-deployment
  labels:
    app: profiling-v4-consumer-vib-add-campaign-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profiling-v4-consumer-vib-add-campaign-profile
  template:
    metadata:
      labels:
        app: profiling-v4-consumer-vib-add-campaign-profile
    spec:
      containers:
        - name: profiling-v4
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $PROFILING_V4; sh prepare_env.sh && python3.8 -u start_profile_consumer_v2.py vib-add-campaign-profile 1"]
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
               name: mobio-secret
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 1Gi
              cpu: 500m
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
          # livenessProbe:
          #   exec:
          #     command:
          #       - /bin/bash
          #       - -c
          #       - ps -ef | grep start_profile_consumer_v2.py | grep -v grep
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    