
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  namespace: mobio
  name: profiling-v4-consumer-e1118-enrich-fb-id-scaledobject
spec:
  scaleTargetRef:
    kind: Deployment
    name: profiling-v4-consumer-e1118-enrich-fb-id-deployment
  pollingInterval: 30
  cooldownPeriod: 300
  maxReplicaCount: 2
  minReplicaCount: 1
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka1:9092,kafka2:9092,kafka3:9092
        consumerGroup: mobio-profiling-consumer-enrich
        topic: e1118-enrich-fb-id
        lagThreshold: '1000'
        offsetResetPolicy: latest
        allowIdleConsumers: 'true'
        version: 2.1.1
    