apiVersion: apps/v1
kind: Deployment
metadata:
  name: ads-audience-result-send-email-command-consumer-deployment
  labels:
    app: ads-audience-result-send-email-command-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ads-audience-result-send-email-command-consumer
  template:
    metadata:
      labels:
        app: ads-audience-result-send-email-command-consumer
    spec:
      containers:
        - name: ads
          image: {image}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["cd $ADS_AUTOMATION_HOME; sh prepare_env.sh && python3.8 -u ads_audience_result_send_email_command_consumer.py"]
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc