apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-event-vib-e140-update-balance-deployment
  labels:
    app: user-event-vib-e140-update-balance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-event-vib-e140-update-balance
  template:
    metadata:
      labels:
        app: user-event-vib-e140-update-balance
    spec:
      containers:
        - name: user-event
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $USER_EVENT_HOME; sh prepare_env.sh && python3.5 -u event_consumer_services.py e140 1"]
          envFrom:
            - configMapRef:
                name: mobio-config
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    