apiVersion: apps/v1
kind: Deployment
metadata:
  name: prof-fac-consumer-trigger-sent-out-deployment
  labels:
    app: prof-fac-consumer-trigger-sent-out
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prof-fac-consumer-trigger-sent-out
  template:
    metadata:
      labels:
        app: prof-fac-consumer-trigger-sent-out
    spec:
      containers:
        - name: profile-factory
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $FACTORY_HOME; sh prepare_env.sh && python3.8 -u start_profile_factory_consumer.py trigger-sent-out trigger-sent-out factory-trigger"]
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
               name: mobio-secret
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
          # livenessProbe:
          #   exec:
          #     command:
          #       - /bin/bash
          #       - -c
          #       - ps -ef | grep start_profile_consumer_v2.py | grep -v grep
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    