apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-event-app-internal-api-deployment
  labels:
    app: dynamic-event-app-internal-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamic-event-app-internal-api
  template:
    metadata:
      labels:
        app: dynamic-event-app-internal-api
    spec:
      containers:
        - name: dynamic-event
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $DYNAMIC_EVENT; sh prepare_env.sh && python3.8 -m uvicorn internal_app:app --host 0.0.0.0 --port 11132 --workers 4"]
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          ports:
            - containerPort: 11132
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
          livenessProbe:
            httpGet:
              port: 11132
              path: /dynamic-event/internal/api/v1.0/ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 4
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dynamic-event-app-internal-api-service
  labels:
    app: dynamic-event-app-internal-api
spec:
  ports:
    - name: old
      port: 11132
    - name: new
      port: 80
      protocol: TCP
      targetPort: 11132
  selector:
    app: dynamic-event-app-internal-api