apiVersion: apps/v1
kind: Deployment
metadata:
 name: vib-scheduler-consumer-change-card-annual-fee-deployment
 labels:
   app: vib-scheduler-consumer-change-card-annual-fee
spec:
 replicas: 1
 selector:
   matchLabels:
     app: vib-scheduler-consumer-change-card-annual-fee
 template:
   metadata:
     labels:
       app: vib-scheduler-consumer-change-card-annual-fee
   spec:
     containers:
       - name: vib-scheduler-consumer-change-card-annual-fee
         image: {image}
         command: ["/bin/sh", "-c"]
         args: ["cd $VIB_SCHEDULER_HOME; sh prepare_env.sh && python3.8 -u vib_consumer_services.py 'vib-process-annual-fee-change' 1"]
         resources:
           requests:
             memory: 70Mi
             cpu: 80m
           limits:
             memory: 1Gi
             cpu: 500m
         envFrom:
           - configMapRef:
               name: mobio-config
           - secretRef:
               name: mobio-secret
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc