apiVersion: apps/v1
kind: Deployment
metadata:
 name: voucher-consume-update-voucher-tenant-deployment
 labels:
   app: voucher-consume-update-voucher-tenant
spec:
 replicas: 1
 selector:
   matchLabels:
     app: voucher-consume-update-voucher-tenant
 template:
   metadata:
     labels:
       app: voucher-consume-update-voucher-tenant
   spec:
     containers:
       - name: voucher
         image: {image}
         imagePullPolicy: Always
         command: ["/bin/sh", "-c"]
         args: ["cd $VOUCHER_HOME; sh prepare_env.sh && python3.8 -u voucher_consume_update_voucher_tenant.py"]
         resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 1Gi
              cpu: 500m
         envFrom:
           - configMapRef:
               name: mobio-config
           - secretRef:
               name: mobio-secret
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc