apiVersion: apps/v1
kind: Deployment
metadata:
 name: voucher-consume-retrieve-code-deployment
 labels:
   app: voucher-consume-retrieve-code
spec:
 replicas: 1
 selector:
   matchLabels:
     app: voucher-consume-retrieve-code
 template:
   metadata:
     labels:
       app: voucher-consume-retrieve-code
   spec:
     containers:
       - name: voucher
         image: {image}
         imagePullPolicy: Always
         command: ["/bin/sh", "-c"]
         args: ["cd $VOUCHER_HOME; sh prepare_env.sh && python3.8 -u voucher_consume_retrieve_code.py"]
         envFrom:
           - configMapRef:
               name: mobio-config
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc