apiVersion: apps/v1
kind: Deployment
metadata:
  name: jb-waiter-base-scheduler-deployment
  labels:
    app: jb-waiter-base-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jb-waiter-base-scheduler
  template:
    metadata:
      labels:
        app: jb-waiter-base-scheduler
    spec:
      containers:
        - name: jb-waiter-base
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $JB_WAITER_HOME; sh prepare_env.sh && python3.8 -u schedule_connector.py"]
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
#          livenessProbe:
#            exec:
#              command:
#                - /bin/bash
#                - -c
#                - ps -ef | grep schedule_connector.py | grep -v grep
#            initialDelaySeconds: 10
#            periodSeconds: 10
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    