
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  namespace: mobio
  name: prof-fac-consumer-factory-jb-bank-t3-account-change-status-scaledobject
spec:
  scaleTargetRef:
    kind: Deployment
    name: prof-fac-consumer-factory-jb-bank-t3-account-change-status-deployment
  pollingInterval: 30
  cooldownPeriod: 300
  maxReplicaCount: 4
  minReplicaCount: 1
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka1:9092,kafka2:9092,kafka3:9092
        consumerGroup: factory-jb-bank-t3-account-change-status
        topic: factory-jb-dist-bank-t3-account
        lagThreshold: '1000'
        offsetResetPolicy: latest
        allowIdleConsumers: 'true'
        version: 2.1.1
    