apiVersion: apps/v1
kind: Deployment
metadata:
 name: loyalty-consumer-update-profile-point-deployment
 labels:
   app: loyalty-consumer-update-profile-point
spec:
 replicas: 1
 selector:
   matchLabels:
     app: loyalty-consumer-update-profile-point
 template:
   metadata:
     labels:
       app: loyalty-consumer-update-profile-point
   spec:
     containers:
       - name: loyalty
         image: {image}
         imagePullPolicy: Always
         command: ["/bin/sh", "-c"]
         args: ["cd $LOYALTY_HOME; sh prepare_env.sh && python3.8 -u loyalty_consumer_service.py loyalty_update_profile_point"]
         resources:
           requests:
             memory: 70Mi
             cpu: 80m
           limits:
             memory: 1Gi
             cpu: 500m
         envFrom:
           - configMapRef:
               name: mobio-config
           - secretRef:
               name: mobio-secret
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc