apiVersion: apps/v1
kind: Deployment
metadata:
 name: loyalty-api-app-deployment
 labels:
   app: loyalty-api-app
spec:
 replicas: 2
 selector:
   matchLabels:
     app: loyalty-api-app
 template:
   metadata:
     labels:
       app: loyalty-api-app
   spec:
     containers:
       - name: loyalty
         image: {image}
         imagePullPolicy: Always
         command: ["/bin/sh", "-c"]
         args: ["cd $LOYALTY_HOME; sh prepare_env.sh && uwsgi --http :11051 --wsgi-file app_loyalty.py --callable app --master --processes 4 -b 65536 --lazy --enable-threads -l 100"]
         envFrom:
           - configMapRef:
               name: mobio-config
         ports:
           - containerPort: 11051
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
         livenessProbe:
           httpGet:
             port: 11051
             path: /api/v1.0/ping
           initialDelaySeconds: 1
           periodSeconds: 5
           timeoutSeconds: 4
           failureThreshold: 3
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
 name: loyalty-api-app-service
 labels:
   app: loyalty-api-app
spec:
 ports:
   - port: 11051
 selector:
   app: loyalty-api-app