apiVersion: apps/v1
kind: Deployment
metadata:
 name: loyalty-consumer-profile-card-update-deployment
 labels:
   app: loyalty-consumer-profile-card-update
spec:
 replicas: 1
 selector:
   matchLabels:
     app: loyalty-consumer-profile-card-update
 template:
   metadata:
     labels:
       app: loyalty-consumer-profile-card-update
   spec:
     containers:
       - name: loyalty
         image: {image}
         imagePullPolicy: Always
         command: ["/bin/sh", "-c"]
         args: ["cd $LOYALTY_HOME; sh prepare_env.sh && python3.5 -u loyalty_consumer_service.py loyalty-update-level-card"]
         envFrom:
           - configMapRef:
               name: mobio-config
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc