apiVersion: apps/v1
kind: Deployment
metadata:
 name: loyalty-api-transaction-app-deployment
 labels:
   app: loyalty-api-transaction-app
spec:
 replicas: 2
 selector:
   matchLabels:
     app: loyalty-api-transaction-app
 template:
   metadata:
     labels:
       app: loyalty-api-transaction-app
   spec:
     containers:
       - name: loyalty
         image: {image}
         imagePullPolicy: Always
         command: ["/bin/sh", "-c"]
         args: ["cd $LOYALTY_HOME; sh prepare_env.sh && uwsgi --http :11053 --wsgi-file app_transaction.py --callable app --master --processes 4 -b 65536 --lazy --enable-threads -l 100"]
         resources:
           requests:
             memory: 30Mi
             cpu: 20m
           limits:
             memory: 1Gi
             cpu: 1000m
         envFrom:
           - configMapRef:
               name: mobio-config
           - secretRef:
               name: mobio-secret
         ports:
           - containerPort: 11053
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
         livenessProbe:
           httpGet:
             port: 11053
             path: /api/v1.0/ping
           initialDelaySeconds: 120
           periodSeconds: 5
           timeoutSeconds: 4
           failureThreshold: 3
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
 name: loyalty-api-transaction-app-service
 labels:
   app: loyalty-api-transaction-app
spec:
 ports:
   - name: old
     port: 11053
   - name: new
     port: 80
     protocol: TCP
     targetPort: 11053
 selector:
   app: loyalty-api-transaction-app