apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-change-deployment
  labels:
    app: survey-change-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey-change-consumer
  template:
    metadata:
      labels:
        app: survey-change-consumer
    spec:
      containers:
        - name: survey
          image: {image}
          command: [ "/bin/sh", "-c" ]
          args: [ "cd $SURVEY_FOLDER_NAME; sh prepare_env.sh && python3.8 -u start_change_status_survey.py" ]
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
            - name: mobio-public-shared-data
              mountPath: /media/data/public_resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
        - name: mobio-public-shared-data
          persistentVolumeClaim:
            claimName: mobio-public-resources-pvc