apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-thumbnail-consumer-sent-html-deployment
  labels:
    app: survey-thumbnail-consumer-sent-html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey-thumbnail-consumer-sent-html
  template:
    metadata:
      labels:
        app: survey-thumbnail-consumer-sent-html
    spec:
      containers:
        - name: survey
          image: {image}
          command: [ "/bin/sh", "-c" ]
          args: [ "cd $SURVEY_FOLDER_NAME; sh prepare_env.sh && python3.8 -u start_generate_data_from_survey_html.py" ]
          envFrom:
            - configMapRef:
                name: mobio-config
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
            - name: mobio-public-shared-data
              mountPath: /media/data/public_resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
        - name: mobio-public-shared-data
          persistentVolumeClaim:
            claimName: mobio-public-resources-pvc
