apiVersion: apps/v1
kind: Deployment
metadata:
 name: survey-app-api-deployment
 labels:
   app: survey-app-api
spec:
 replicas: 2
 selector:
   matchLabels:
     app: survey-app-api
 template:
   metadata:
     labels:
       app: survey-app-api
   spec:
     containers:
       - name: survey
         image: {image}
         command: ["/bin/sh", "-c"]
         args: ["cd $SURVEY_FOLDER_NAME; sh prepare_env.sh && uwsgi --http :11230 --wsgi-file survey_app.py --callable app --master --processes 4 -b 65536 --lazy --enable-threads"]
         resources:
           requests:
             memory: 30Mi
             cpu: 20m
           limits:
             memory: 1Gi
             cpu: 500m
         envFrom:
           - configMapRef:
               name: mobio-config
           - secretRef:
               name: mobio-secret
         ports:
           - containerPort: 11230
#         resources:
#           requests:
#             memory: 70Mi
#             cpu: 80m
#           limits:
#             memory: 1Gi
#             cpu: 500m
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
           - name: mobio-public-shared-data
             mountPath: /media/data/public_resources/
         livenessProbe:
           httpGet:
             port: 11230
             path: /api/v1.0/ping
           initialDelaySeconds: 1
           periodSeconds: 5
           timeoutSeconds: 4
           successThreshold: 1
           failureThreshold: 3
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc
       - name: mobio-public-shared-data
         persistentVolumeClaim:
           claimName: mobio-public-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
 name: survey-app-api-service
 labels:
   app: survey-app-api
spec:
 ports:
  - name: old
    port: 11230
  - name: new
    port: 80
    protocol: TCP
    targetPort: 11230
 selector:
   app: survey-app-api