apiVersion: apps/v1
kind: Deployment
metadata:
 name: mail-client-webhook-app-api-deployment
 labels:
   app: mail-client-webhook-app-api
spec:
 replicas: 2
 selector:
   matchLabels:
     app: mail-client-webhook-app-api
 template:
   metadata:
     labels:
       app: mail-client-webhook-app-api
   spec:
     containers:
       - name: mail-client
         image: {image}
         imagePullPolicy: Always
         command: ["/bin/sh", "-c"]
         args: ["cd $PERSONAL_MAIL_HOME; sh prepare_env.sh && uwsgi --http :11301 --wsgi-file app_webhook_api.py --callable app_webhook --master --processes 4 -b 65536 --lazy --enable-threads -l 100"]
         envFrom:
           - configMapRef:
               name: mobio-config
           - secretRef:
               name: mobio-secret
         ports:
           - containerPort: 11301
         resources:
           requests:
             memory: 70Mi
             cpu: 80m
           limits:
             memory: 1Gi
             cpu: 500m
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
           - name: mobio-public-shared-data
             mountPath: /media/data/public_resources/
         livenessProbe:
           httpGet:
             port: 11301
             path: /mailclient/webhook/api/v1.0/ping
           initialDelaySeconds: 120
           periodSeconds: 5
           timeoutSeconds: 4
           failureThreshold: 3
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc
       - name: mobio-public-shared-data
         persistentVolumeClaim:
           claimName: mobio-public-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
 name: mail-client-webhook-app-api-service
 labels:
   app: mail-client-webhook-app-api
spec:
 ports:
   - name: old
     port: 11301
   - name: new
     port: 80
     protocol: TCP
     targetPort: 11301
 selector:
   app: mail-client-webhook-app-api