apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-event-consumer-profile-event-dynamic-p1-deployment
  labels:
    app: dynamic-event-consumer-profile-event-dynamic-p1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamic-event-consumer-profile-event-dynamic-p1
  template:
    metadata:
      labels:
        app: dynamic-event-consumer-profile-event-dynamic-p1
    spec:
      containers:
        - name: dynamic-event
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $DYNAMIC_EVENT; sh prepare_env.sh && python3.8 -u start_dynamic_event_consumers.py profile-event-dynamic-p1 1"]
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
          # livenessProbe:
          #   exec:
          #     command:
          #       - /bin/bash
          #       - -c
          #       - ps -ef | grep start_dynamic_event_consumers.py | grep -v grep
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    