apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-event-consumer-upsert-profile-with-callback-deployment
  labels:
    app: dynamic-event-consumer-upsert-profile-with-callback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamic-event-consumer-upsert-profile-with-callback
  template:
    metadata:
      labels:
        app: dynamic-event-consumer-upsert-profile-with-callback
    spec:
      containers:
        - name: dynamic-event
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $DYNAMIC_EVENT; sh prepare_env.sh && python3.8 -u start_dynamic_event_consumers.py upsert-profile-with-callback 1"]
          envFrom:
            - configMapRef:
                name: mobio-config
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
          # livenessProbe:
          #   exec:
          #     command:
          #       - /bin/bash
          #       - -c
          #       - ps -ef | grep start_dynamic_event_consumers.py | grep -v grep
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    