apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-web-push-api-deployment
  labels:
    app: wp-web-push-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-web-push-api
  template:
    metadata:
      labels:
        app: wp-web-push-api
    spec:
      containers:
        - name: wp-web-push-api
          image: {image}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["cd $WEB_PUSH_API; sh prepare_env.sh && uwsgi --http :11180 --wsgi-file app.py --callable app --master --processes 4 -b 65536 --lazy --enable-threads"]
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 1Gi
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          ports:
            - containerPort: 11180
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
          livenessProbe:
            httpGet:
              port: 11180
              path: /api/v1.0/ping
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 4
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wp-web-push-api-services
  labels:
    app: wp-web-push-api
spec:
  ports:
    - name: old
      port: 11180
    - name: new
      port: 80
      protocol: TCP
      targetPort: 11180
  selector:
    app: wp-web-push-api
