apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-listener-consumer-deployment-process-webhook-command
  labels:
    app: social-listener-consumer-process-webhook-command
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-listener-consumer-process-webhook-command
  template:
    metadata:
      labels:
        app: social-listener-consumer-process-webhook-command
    spec:
      containers:
        - name: social-listener-consumer-process-webhook-command
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $SOCIAL_LISTENER_HOME; sh prepare_env.sh && python3.5 -u social_listener_process_webhook_command_consumer.py"]
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc