apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiling-v4-app-internal-api-deployment
  labels:
    app: profiling-v4-app-internal-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profiling-v4-app-internal-api
  template:
    metadata:
      labels:
        app: profiling-v4-app-internal-api
    spec:
      containers:
        - name: profiling-v4
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $PROFILING_V4; sh prepare_env.sh && uwsgi --http :11091 --wsgi-file app_profile_thirdparty.py --callable app --master --processes 4 -b 65536 --lazy --enable-threads"]
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          ports:
            - containerPort: 11091
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
          livenessProbe:
            httpGet:
              port: 11091
              path: /profiling/internal/v3.0/ping
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 4
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: profiling-v4-app-internal-api-service
  labels:
    app: profiling-v4-app-internal-api
spec:
#  clusterIP: None
  ports:
    - name: old
      port: 11091
    - name: new
      port: 80
      protocol: TCP
      targetPort: 11091
  selector:
    app: profiling-v4-app-internal-api