apiVersion: apps/v1
kind: Deployment
metadata:
 name: user-event-app-api-deployment
 labels:
   app: user-event-app-api
spec:
 replicas: 1
 selector:
   matchLabels:
     app: user-event-app-api
 template:
   metadata:
     labels:
       app: user-event-app-api
   spec:
     containers:
       - name: user-event
         image: {image}
         command: ["/bin/sh", "-c"]
         args: ["cd $USER_EVENT_HOME; sh prepare_env.sh && uwsgi --http :11130 --wsgi-file app_user_event.py --callable app --master --processes 4 -b 65536 --lazy --enable-threads"]
         envFrom:
           - configMapRef:
               name: mobio-config
           - secretRef:
               name: mobio-secret
         resources:
           requests:
             memory: 70Mi
             cpu: 80m
           limits:
             memory: 1Gi
             cpu: 500m
         ports:
           - containerPort: 11130
         volumeMounts:
           - name: mobio-shared-data
             mountPath: /media/data/resources/
     imagePullSecrets:
       - name: registrypullsecret
     volumes:
       - name: mobio-shared-data
         persistentVolumeClaim:
           claimName: mobio-resources-pvc
---
apiVersion: v1
kind: Service
metadata:
 name: user-event-app-api-service
 labels:
   app: user-event-app-api
spec:
 ports:
   - name: old
     port: 11130
   - name: new
     port: 80
     protocol: TCP
     targetPort: 11130
 selector:
   app: user-event-app-api
