apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-event-consumer-e114-jb-ms-opened-input-handler-deployment
  labels:
    app: user-event-consumer-e114-jb-ms-opened-input-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-event-consumer-e114-jb-ms-opened-input-handler
  template:
    metadata:
      labels:
        app: user-event-consumer-e114-jb-ms-opened-input-handler
    spec:
      containers:
        - name: user-event
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $USER_EVENT_HOME; sh prepare_env.sh && python3.8 -u event_consumer_services.py e114-jb-ms-opened-input-handler"]
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 1Gi
              cpu: 500m
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    