apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-event-schedule-resent-err-logs-deployment
  labels:
    app: user-event-schedule-resent-err-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-event-schedule-resent-err-logs
  template:
    metadata:
      labels:
        app: user-event-schedule-resent-err-logs
    spec:
      containers:
        - name: user-event
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $USER_EVENT_HOME; sh prepare_env.sh && PYTHONPATH=./ python3.8 -u run_scheduler/factory_scheduler_resent_err_logs.py "]
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    