apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobio-report-schedule-export-excel-deployment
  labels:
    app: mobio-report-schedule-export-excel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobio-report-schedule-export-excel
  template:
    metadata:
      labels:
        app: mobio-report-schedule-export-excel
    spec:
      containers:
        - name: mobio-report
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $MOBIO_REPORT_HOME; sh prepare_env.sh && python3.8 -u schedule_services.py export-excel"]
          resources:
            requests:
              memory: 30Mi
              cpu: 20m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    