apiVersion: apps/v1
kind: Deployment
metadata:
  name: digienty-csm-register-device-cmd-deployment
  labels:
    app: digienty-csm-register-device-cmd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digienty-csm-register-device-cmd
  template:
    metadata:
      labels:
        app: digienty-csm-register-device-cmd
    spec:
      containers:
        - name: bsd
          imagePullPolicy: Always
          image: {image}
          command: ["/bin/sh", "-c"]
          args: ["cd $WEB_PUSH_API; sh prepare_env.sh && python3.8 -u consumer_services.py digienty-device-register-cmd 1"]
          resources:
            requests:
              memory: 70Mi
              cpu: 80m
            limits:
              memory: 1Gi
              cpu: 500m
          envFrom:
            - configMapRef:
                name: mobio-config
            - secretRef:
                name: mobio-secret
          volumeMounts:
            - name: mobio-shared-data
              mountPath: /media/data/resources/
      imagePullSecrets:
        - name: registrypullsecret
      volumes:
        - name: mobio-shared-data
          persistentVolumeClaim:
            claimName: mobio-resources-pvc
    